core/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'worksmart.views.home', name='home'),
    #url(r'^$', views.trend, name='trend'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
)

enterprise/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
    # Examples:
    url(r'^projects$', views.ProjectList.as_view(), name='enterprise.projects'),
    url(r'^company/(?P<pk>\d+)/$', views.CompanyProjectList.as_view(), name='enterprise.company'),
    url(r'^submissions$', views.SubmissionList.as_view(), name='enterprise.submissions'),
    url(r'^reviews$', views.ApplicationReviewList.as_view(), name='enterprise.reviews'),
    url(r'^evaluations', views.SelfEvaluationList.as_view(), name='enterprise.evaluations'),
    url(r'^selections', views.SelectionList.as_view(), name='enterprise.selections'),
    url(r'^notifications', views.NotificationList.as_view(), name='enterprise.notifications'),
    url(r'^notification/data/$', views.notification_data, name='enterprise.notification_data'),
    url(r'^project/add/$', views.create_project, name='enterprise.project.add'),
    url(r'^project/sk/$', views.project_sk, name='enterprise.project.sk'),
    url(r'^project/(?P<pk>\d+)/delete/$', views.delete_project, name='enterprise.project.delete'),
    url(r'^project/(?P<pk>\d+)/$', views.ProjectUpdate.as_view(), name='enterprise.project.update'),
    url(r'^projects/(?P<project_id>\d+)/$', views.project_detail, name='enterprise.project.detail'),
    url(r'^projects/(?P<project_id>\d+)/progress/$', views.project_progress, name='enterprise.project.progress'),
    url(r'^projects/progress/$', views.project_progress_data, name='enterprise.project.progress.data'),
    url(r'^projects/(?P<project_id>\d+)/submission/$', views.project_submission, name='enterprise.project.submission'),
    url(r'^projects/(?P<project_id>\d+)/submission/preview/$', views.project_submission_preview, name='enterprise.project.submission.preview'),
    url(r'^projects/(?P<project_id>\d+)/submission/pdf/$', views.project_submission_pdf, name='enterprise.project.submission.pdf'),
    url(r'^submissions/commit/$', views.submission_commit, name='enterprise.submission.commit'),
    url(r'^submissions/approve/$', views.submission_approve, name='enterprise.submission.approve'),
    url(r'^submissions/deny/$', views.submission_deny, name='enterprise.submission.deny'),
    url(r'^submission/add/$', views.create_submission, name='enterprise.submission.add'),
    url(r'^submission/(?P<pk>\d+)/$', views.SubmissionUpdate.as_view(), name='enterprise.submission.update'),
    url(r'^projects/(?P<project_id>\d+)/review/$', views.project_review, name='enterprise.project.review'),
    url(r'^projects/(?P<project_id>\d+)/review/pdf/$', views.project_review_pdf, name='enterprise.project.review.pdf'),
    url(r'^reviews/commit/$', views.review_commit, name='enterprise.review.commit'),
    url(r'^review/add/$', views.create_review, name='enterprise.review.add'),
    url(r'^review/(?P<pk>\d+)/$', views.ApplicationReviewUpdate.as_view(), name='enterprise.review.update'),
    url(r'^review/(?P<project_id>\d+)/approve/$', views.review_approve, name='enterprise.review.approve'),
    url(r'^review/(?P<project_id>\d+)/deny/$', views.review_deny, name='enterprise.review.deny'),
    url(r'^review/(?P<project_id>\d+)/summary/$', views.review_summary, name='enterprise.review.summary'),
    url(r'^review/(?P<project_id>\d+)/photo/$', views.review_photo, name='enterprise.review.photo'),
    url(r'^photo/(?P<pk>\d+)/delete/$', views.delete_review_photo, name='enterprise.review.photo.delete'),
    url(r'^project/(?P<project_id>\d+)/achievement/pictures/$', views.project_achievement_pictures, name='enterprise.project.achievement.pictures'),
    url(r'^project/(?P<project_id>\d+)/achievement/$', views.project_achievement, name='enterprise.project.achievement'),
    url(r'^project/(?P<project_id>\d+)/summary/$', views.project_summary_report, name='enterprise.project.summary'),
    url(r'^project/(?P<project_id>\d+)/presentation/$', views.project_presentation, name='enterprise.project.presentation'),
    url(r'^project/(?P<project_id>\d+)/(?P<element_id>\d+)/pdf/element$', views.element_evaluation_pdf, name='enterprise.project.pdf.element'),
    url(r'^project/(?P<project_id>\d+)/pdf/batch$', views.batch_evaluation_pdf, name='enterprise.project.pdf.batch'),
    url(r'^project/(?P<project_id>\d+)/pdf/stage$', views.stage_evaluation_pdf, name='enterprise.project.pdf.stage'),
    url(r'^project/(?P<project_id>\d+)/pdf/unit$', views.unit_evaluation_pdf, name='enterprise.project.pdf.unit'),
    # url(r'^project/(?P<project_id>\d+)/form$', views.project_evaluation_form, name='enterprise.project.form'),
    url(r'^project/(?P<project_id>\d+)/stage', views.project_stage, name='enterprise.project.stage'),
    url(r'^project/(?P<project_id>\d+)/(?P<element_id>\d+)/print/element/$', views.element_evaluation_print, name='enterprise.project.print.element'),
    url(r'^project/(?P<project_id>\d+)/print/batch/$', views.batch_evaluation_print, name='enterprise.project.print.batch'),
    url(r'^project/(?P<project_id>\d+)/print/stage/$', views.stage_evaluation_print, name='enterprise.project.print.stage'),
    url(r'^project/(?P<project_id>\d+)/print/unit/$', views.unit_evaluation_print, name='enterprise.project.print.unit'),
    url(r'^projects/(?P<project_id>\d+)/evaluation/$', views.project_evaluation, name='enterprise.project.evaluation'),
    url(r'^projects/(?P<project_id>\d+)/element/add/$', views.create_element_evaluation_form, name='enterprise.project.element.add'),
    url(r'^element/(?P<pk>\d+)/$', views.ElementEvaluationFormUpdate.as_view(), name='enterprise.project.element.update'),
    url(r'^projects/(?P<project_id>\d+)/batch/add/$', views.create_batch_evaluation_form, name='enterprise.project.batch.add'),
    url(r'^projects/(?P<project_id>\d+)/(?P<stage_id>\d+)/batch/create/$', views.create_batch, name='enterprise.stage.batch.create'),
    url(r'^projects/(?P<project_id>\d+)/(?P<batch_id>\d+)/batch/detail', views.batch_detail, name='enterprise.stage.batch.detail'),
    url(r'^projects/(?P<project_id>\d+)/(?P<stage_id>\d+)/batch', views.stage_batch, name='enterprise.project.batch'),
    url(r'^batch/(?P<pk>\d+)/$', views.BatchEvaluationFormUpdate.as_view(), name='enterprise.project.batch.update'),
    url(r'^projects/(?P<project_id>\d+)/stage/add/$', views.create_stage_evaluation_form, name='enterprise.project.stage.add'),
    url(r'^projects/(?P<project_id>\d+)/stages/add/$', views.create_stage, name='enterprise.project.stages.add'),
    url(r'^stage/(?P<pk>\d+)/$', views.StageEvaluationFormUpdate.as_view(), name='enterprise.project.stage.update'),
    url(r'^projects/(?P<project_id>\d+)/unit/add/$', views.create_unit_evaluation_form, name='enterprise.project.unit.add'),
    url(r'^unit/(?P<pk>\d+)/$', views.UnitEvaluationFormUpdate.as_view(), name='enterprise.project.unit.update'),
    url(r'^projects/(?P<project_id>\d+)/monitor/$', views.project_monitor, name='enterprise.project.monitor'),
    url(r'^projects/(?P<project_id>\d+)/selection/$', views.project_selection, name='enterprise.project.selection'),
    url(r'^projects/(?P<project_id>\d+)/pm10/$', views.project_pm10, name='enterprise.project.pm10'),
    url(r'^projects/(?P<project_id>\d+)/pm10/data/$', views.pm10_data, name='enterprise.project.pm10_data'),
    url(r'^projects/(?P<project_id>\d+)/noise/$', views.project_noise, name='enterprise.project.noise'),
    url(r'^projects/(?P<project_id>\d+)/log/$', views.project_log, name='enterprise.project.log'),
)

greenbuilding/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'accounts.views.login'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^core/', include('core.urls')),
    url(r'^enterprise/', include('enterprise.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser,UserManager, PermissionsMixin,AbstractUser)
from django.core import validators
from django.utils import timezone
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.shortcuts import get_object_or_404


# Create your models here.
#class UserProfile(AbstractBaseUser, PermissionsMixin):
#    email = models.EmailField(verbose_name= 'email address', max_length=255, unique=True)
#    username = models.CharField(_('username'), max_length=30, unique=True,
#        help_text=_('Required. 30 characters or fewer. Letters, digits and '
#                    '@/./+/-/_ only.'),
#        validators=[
#            validators.RegexValidator(r'^[\w.@+-]+$', _('Enter a valid username.'), 'invalid')
#        ])
#    company = models.CharField(_('company'), max_length= 255, blank=False)
#    is_active = models.BooleanField(default=True)
#    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
#
#    objects = UserManager()
#    USERNAME_FIELD = 'username'
#    REQUIRED_FIELDS = ['company','email']
#
#    # On Python 3: def __str__(self):
#    def __unicode__(self):
#        return self.username
#
#    def get_full_name(self):
#        return self.company
#
#    def get_short_name(self):
#        "Returns the short name for the user."
#        return self.username
#
#    def has_perm(self, perm, obj=None):
#        return True
#
#    def has_module_perms(self, app_label):
#        return True


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    company = models.CharField(verbose_name=_('Company'), max_length=255, blank=False)
    location = models.CharField(verbose_name=_("location"), max_length=256, blank=True, null=True)
    contact = models.CharField(verbose_name=_('contact'), max_length=32, blank=True, null=True)
    phone = models.CharField(verbose_name=_('phone'), max_length=32, blank=True, null=True)
    is_company = models.BooleanField(verbose_name=_('is_company'), default=True)

    def __unicode__(self):
        return self.company


@receiver(post_save, sender=User)
def create_profile(sender, instance, **kwargs):
    if kwargs['created']:
        #create UserProfile on User created event
        user = User.objects.get(username=instance.username)
        p = UserProfile(user=user, company=instance.username)
        p.save()

@receiver(pre_delete, sender=User)
def delete_profile(sender, instance, **kwargs):
    user = User.objects.get(username=instance.username)
    p = get_object_or_404(UserProfile, user_id=user.pk)
    p.delete()

enterprise/forms.py
from django.forms import ModelForm
from models import (Project, Submission, ApplicationReview, ElementEvaluationForm, BatchEvaluationForm, StageEvaluationForm,
                    UnitEvaluationForm, Stage, Batch)


# Create form from models
class ProjectForm(ModelForm):
    class Meta:
        model = Project
        #fields = ['name', 'description', 'location', 'area', 'cost', 'structure_type', 'start_date', 'end_date',
        #          'construct_company', 'postal_address', 'zipcode']
        #exclude = ['user']
        fields = '__all__'


class SubmissionForm(ModelForm):
    class Meta:
        model = Submission
        exclude = ['date']
        fields = '__all__'


class ReviewForm(ModelForm):
    class Meta:
        model = ApplicationReview
        exclude = ['date']
        fields = '__all__'


class ElementEvaluationFormForm(ModelForm):
    class Meta:
        model = ElementEvaluationForm
        exclude = ['date']
        fields = '__all__'


class BatchEvaluationFormForm(ModelForm):
    class Meta:
        model = BatchEvaluationForm
        exclude = ['date']
        fields = '__all__'


class StageEvaluationFormForm(ModelForm):
    class Meta:
        model = StageEvaluationForm
        exclude = ['date']


class UnitEvaluationFormForm(ModelForm):
    class Meta:
        model = UnitEvaluationForm
        exclude = ['date']


class StageForm(ModelForm):
    class Meta:
        model = Stage
        fields = '__all__'


class BatchForm(ModelForm):
    class Meta:
        model = Batch
        fields = '__all__'

enterprise/templates/batch_evaluation_print.html
<html>
{% load staticfiles%}

<head>
    <script src="{% static 'vendor/pdf.js' %}"></script>
    <script src="{% static 'js/pdf.form.js' %}"></script>
</head>
<body>
  <canvas id="the-canvas" style="border:1px  solid black"></canvas>

  <script>

    //
    // NOTE:
    // Modifying the URL below to another server will likely *NOT* work. Because of browser
    // security restrictions, we have to use a file server with special headers
    // (CORS) - most servers don't support cross-origin browser requests.
    //
{#    var url = 'http://cdn.mozilla.net/pdfjs/helloworld.pdf';#}

    PDFJS.workerSrc = "{% static 'vendor/pdf.worker.js' %}";
   render_pdf("/media/review/form/batch/{{ project_id }}.pdf");

  </script>
  
</body>
</html>

enterprise/templates/company_detail.html
{% extends "enterprise_base.html" %}
{% load i18n staticfiles%}

{% block main %}
    <div class="container">
        <label>{% trans "Company" %}</label><p>{{ object.company }}</p>
        <label>{% trans "Location" %}</label><p>{{ object.location }}<br></p>
        <label>{% trans "contact" %}</label><p>{{ object.contact }}<br></p>
        <label>{% trans "phone" %}</label><p>{{ object.phone }}<br></p>
    </div>
{% endblock %}

enterprise/templates/create_project.html
{% extends "enterprise_base.html" %}

{% block main %}
    <div>
    {{ block.super }}
    <form method="post"  role="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-actions">
            {% block account_form_actions %}
            <input class="btn btn-success btn-small form-control" type="submit" value="{{ title }}">
            {% endblock %}
        </div>
    </form>
    </div>
{%  endblock %}

{% block extra_js %}
    {{ block.super }}
    <script>
    $(document).ready(function() {
        // Event listener to the two range filtering inputs to redraw on input
        $('#id_PrjNum').blur( function() {
            var prjNum = $('#id_PrjNum').val();
            console.log(prjNum);
            $.get('{% url "enterprise.project.sk" %}', {'prjNum': prjNum}, function (data){
                            console.log(data);
                var status = data.status;
                if (status == 'OK'){
                    $('#id_name').val(data.name);
                    $('#id_area').val(data.area);
                    $('#id_cost').val(data.cost);
                    $('#id_owner').val(data.construct_company);
                    $('#id_begin_date').val(data.begin_date);
                    $('#id_end_date').val(data.end_date);
                    $('#id_location').val(data.location);
                    $('#id_construct_company').val("{{ enterprise }}");
                } else {
                    alert("项目编码不存在!");
                    $('#id_name').val('');
                    $('#id_area').val('');
                    $('#id_cost').val('');
                    $('#id_owner').val('');
                    $('#id_begin_date').val('');
                    $('#id_end_date').val('');
                    $('#id_location').val('');
                }

            });

        } );
    } );
    </script>
{% endblock %}

enterprise/templates/enterprise_base.html
{% extends "core_base.html" %}
{% load i18n %}

{% block left_panel %}
<ul class="nav nav-pills nav-stacked">
  <li class="active"><a href="{% url "enterprise.projects" %}">{% trans "Project List"%}</a></li>
  <li><a href="{% url "enterprise.submissions" %}">{% trans "Submission List"%}</a></li>
  <li><a href="{% url "enterprise.reviews" %}">{% trans "Review List"%}</a></li>
</ul>
{% endblock %}

{% block main %}
{% endblock %}

enterprise/templates/list_base.html
{% extends "enterprise_base.html" %}
{% load i18n %}

{% block main %}
{% block toolbar %}{% endblock %}

{% block list %}
{% endblock %}

{#<div class="pagination">#}
{#    <span class="step-links">#}
{#    {% if submissions.has_previous %}#}
{#    <a href="?page={{ submissions.previous_page_number }}">previous</a>#}
{#    {% endif %}#}
{#    <span class="current">#}
{#    Page {{ submissions.number }} of {{ submissions.paginator.num_pages }}.#}
{#    </span>#}
{#    {% if submissions.has_next %}#}
{#    <a href="?page={{ submissions.next_page_number }}">next</a>#}
{#    {% endif %}#}
{#    </span>#}
{#</div>#}

{% endblock %}

enterprise/templates/project_achievement.html
{% extends "project_base.html" %}
{% load i18n staticfiles project_filters%}

{% block extra_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'slick.js/slick/slick.css' %}">
    <link rel="stylesheet" href="{% static 'magnific-popup/dist/magnific-popup.css' %}">
    <style>
    figure {
        position: relative;
        display: inline-block;
    }

    figcaption {
        display: none;
        position: absolute;
        left:100px;
        bottom: 20px;
        right: 0;
{#        background-color: rgba(0,0,0,.15);#}
    }

    figure:hover img {
        opacity: .7;
    }

    figure:hover figcaption {
        display: block;
    }
    </style>
{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script src="{% static 'slick.js/slick/slick.min.js' %}"></script>
    <script src="{% static 'jquery-cookie/jquery.cookie.js' %}"></script>
    <script src="{% static 'jquery-file-upload/js/vendor/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'jquery-file-upload/js/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'jquery-file-upload/js/jquery.fileupload.js' %}"></script>
    <script src="{% static 'magnific-popup/dist/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'handlebars/handlebars.min.js' %}"></script>

    <script id="pictures_template" type="text/x-handlebars-template">
    {% verbatim %}
          {{#each [] }}
            <a href="{{ this.url }}">
                <img src="{{ this.url }}" style="width: 20%; height: 20%"/>
            </a>
            <button class="btn btn-primary remove-pictures" id="{{ this.pk }}"><i class="fa fa-times fa"></i>删除</button>
          {{/each}}
    {% endverbatim %}
    </script>

    <script id="pictures_template2" type="text/x-handlebars-template">
    {% verbatim %}
          {{#each [] }}
            <figure>
                <img src="{{ this }}" style="width: 20%; height: 20%"/>
                <figcaption><a class="btn btn-primary" id="test"><i class="fa fa-youtube-play"></i>删除</a></figcaption>
            </figure>
          {{/each}}
    {% endverbatim %}
    </script>

    <script>
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
         }

        function loadPhotos(){
            console.log("load photos");
{#            console.log("{{ review.id }}");#}
            $.get('{% url "enterprise.project.achievement.pictures" review.id %}',function(data){
                console.log(data);
                var source   = $("#pictures_template").html();
                var template = Handlebars.compile(source);
                var html    = template(data);
{#                console.log(html);#}
                $('#popup-gallery').html(html);
            })
        }

        $(document).ready(function(){
            var csrf_token = $.cookie('csrftoken');

{#           $(".your-class").slick({#}
{#                dots: true,#}
{#               autoplay:true,#}
{#               autoplaySpeed:300,#}
{#               speed:500#}
{#               arrows:true,#}
{#                 prevArrow:$(".slick-prev"),#}
{#               nextArrow:$(".slick-next")#}
{#               lazyLoad: 'ondemand',#}
{#              slidesToShow: 3,#}
{#              slidesToScroll: 1#}
{#        });#}

        $('#fileupload').fileupload({
            dataType: 'json',
            acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
            maxNumberOfFiles:2,
            crossDomain: false,
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", csrf_token);
                }
            },
            done: function (e, data) {
{#                console.log(data);#}
{#                $.each(data.result.files, function (index, file) {#}
{#                    $('<p/>').text(file.name).appendTo(document.body);#}
{#                });#}
                console.log("done");
{#                loadPhotos();#}
            },
            progressall: function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
{#                console.log(progress);#}
                $('#progress .progress-bar').css(
                    'width',
                    progress + '%'
                );
            },
            stop: function(e,data){
                console.log("upload finished");
                loadPhotos();
            }
        });

        $('#popup-gallery').magnificPopup({
          delegate: 'a', // child items selector, by clicking on it popup will open
          type: 'image',
          gallery:{enabled:true}
          // other options
        });

        loadPhotos();

        //use on() to replace click() for events of dynamically created element
        $("body").on('click', '.remove-pictures', function() {
            var url = "{% url 'enterprise.review.photo.delete' pk=99999 %}";
            url = url.replace(/99999/, $(this).attr("id"));
            console.log($(this).attr("id"));
            $.post(url,{csrfmiddlewaretoken:csrf_token}, function(data){
                console.log(data);
                loadPhotos();
            })
        });

        });
    </script>
{% endblock %}

{% block left_panel %}
    {% include "review_left_panel.html" %}
{% endblock %}

{% block project_main %}
{% if review.id != 99999 %}
<div class="container">
    <label>{% trans "Project" %}</label><p>{{ review.project.name }}<br></p>
    <label>{% trans "Grade" %}</label><p>{{ review.grade }}<br></p>
    <label>{% trans "Approved" %}</label><p id="approved">{{ review.approved |approve_state}}<br></p>
    <label>{% trans "Achievement" %}</label>
</div>
<div>
    <video id="example_video_1"
      controls preload="auto" width="640" height="200"
      poster="/static/images/oceans-clip.png">
     <source src="/media/{{ review.achievement }}" type='video/mp4' />
     <source src="http://video-js.zencoder.com/oceans-clip.webm" type='video/webm' />
     <source src="http://video-js.zencoder.com/oceans-clip.ogv" type='video/ogg' />
     <p>To view this video please enable JavaScript, and consider upgrading to a web browser that
         <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
     </p>
    </video>
</div>

<div>
    <div>
        <input id="fileupload" type="file" name="files"  accept="image/png,image/gif,image/jpg,image/jpeg"
               data-url="{% url 'enterprise.review.photo' review.id%}" multiple>
    </div>
    <!-- The global progress bar -->
    <div id="progress" class="progress">
        <div class="progress-bar progress-bar-success"></div>
    </div>
</div>

{#<div class="your-class slider">#}
{#{% for picture in pictures %}#}
{#     <div ><img src="/media/{{ picture.file }}"></div>#}
{#{% endfor %}#}
{#</div>#}

{#<div class="popup-gallery">#}
{#{% for picture in pictures %}#}
{#    <a href="/media/{{ picture.file }}">#}
{#        <img src="/media/{{ picture.file }}" alt="{{ picture.file }}"  style="width: 20%; height: 20%"/>#}
{#    </a>#}
{#{% endfor %}#}
{#</div>#}

<div id="popup-gallery">
</div>

{#<figure>#}
{#    <img src="http://127.0.0.1:8000/media/pictures/ryzg_1.jpg" style="width: 20%; height: 20%"/>#}
{#    <figcaption><a class="btn btn-primary" id="test"><i class="fa fa-youtube-play"></i>{% trans "Remove" %}</a></figcaption>#}
{#</figure>#}

{% endif %}
{% endblock %}

enterprise/templates/project_base.html
{% extends "enterprise_base.html" %}
{% load i18n %}

{% block main %}
{% block project_tab %}
<ul class="nav nav-pills">
    <li><a href="{% url "enterprise.project.detail" project_id%}">{% trans "Project Summary"%}</a></li>
    <li><a href="{% url "enterprise.project.submission" project_id%}">{% trans "Submission"%}</a></li>
{#    <li  class="dropdown">#}
{#        <a class="dropdown-toggle" data-toggle="dropdown" href="{% url "enterprise.project.monitor" project_id%}">{% trans "Process Control"%}</a>#}
{#        <ul class="dropdown-menu">#}
{#            <li><a href="{% url "enterprise.project.evaluation" project_id%}">{% trans "Self Evaluation"%}</a></li>#}
{#            <li class="divider"></li>#}
{#            <li><a href="{% url "enterprise.project.monitor" project_id%}">{% trans "Process Monitor" %}</a></li>#}
{#          </ul>#}
{#    </li>#}
    <li><a href="{% url "enterprise.project.review" project_id%}">{% trans "Application Review"%}</a></li>
    <li><a href="{% url "enterprise.project.selection" project_id%}">{% trans "Selection"%}</a></li>
    <li><a href="{% url "enterprise.project.log" project_id%}">{% trans "Logs"%}</a></li>
</ul>
{% endblock %}

{% block project_main %}
{% endblock %}

{% endblock %}

enterprise/templates/project_evaluation.html
{% extends "project_base.html" %}
{% load i18n %}

{% block project_main %}
    <div class="container">
        <label>{% trans "Project" %}</label><p>{{ submission.project.name }}<br></p>
        <label>{% trans "Grade" %}</label><p>{{ submission.grade }}<br></p>
    </div>
{% endblock %}

enterprise/templates/self_evaluation_list.html
{% extends "list_base.html" %}
{% load i18n %}

{% block left_panel %}
<ul class="nav nav-pills nav-stacked">
  <li class="active"><a href="{% url "enterprise.evaluations" %}">{% trans "Self Evaluation" %}</a></li>
</ul>
{% endblock %}

{% block list %}
<table class="table table-hover table-bordered">
    <thead>
        <th>{% trans "Project" %}</th>
    </thead>
    {% for p in projects %}
        <tr>
            <td>{{ p.project.name|upper }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

enterprise/templates/submission_detail.html
{% extends "enterprise_base.html" %}
{% load i18n %}


{% block main %}
{% endblock %}

enterprise/templates/unit_evaluation_print.html
<html>
{% load staticfiles%}
<head>
    <link rel="stylesheet" href="{% static 'pace/themes/pace-theme-barber-shop.css' %}">
    <script src="{% static 'vendor/pdf.js' %}"></script>
    <script src="{% static 'pace/pace.min.js' %}"></script>
    <script src="{% static 'js/pdf.form.js' %}"></script>
</head>
<body>
  <canvas id="the-canvas" style="border:1px  solid black"></canvas>

  <script>

    //
    // NOTE:
    // Modifying the URL below to another server will likely *NOT* work. Because of browser
    // security restrictions, we have to use a file server with special headers
    // (CORS) - most servers don't support cross-origin browser requests.
    //
{#    var url = 'http://cdn.mozilla.net/pdfjs/helloworld.pdf';#}

    PDFJS.workerSrc = "{% static 'vendor/pdf.worker.js' %}";
   render_pdf("/media/review/form/unit/{{ project_id }}.pdf");

  </script>
  
</body>
</html>